# Site settings
title: Devblog
email: felipelucena22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Felipe Lucena is a Computer Science bachelor at UNICAP and Currently working at C.E.S.A.R (Recife center for advanced studies and systems).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://felipebelucena.github.io" # the base hostname & protocol for your site
twitter_username: felipebelucena
github_username:  felipebelucena

# Build settings
markdown: kramdown

# Custom vars
version:        1.0.0
github:
repo:           https://github.com/felipebelucena/blog 
